### ISSUE TITLE
Missing font configuration for Ignition 8

### ISSUE THREAD

**Issue by bgreat** [thirdgen88/ignition-docker#10]
The Ignition 8 image does not have fontconfig and base set of fonts installed. Without the font configuration, scheduled reports will not execute on the gateway.

Thank you,
Bill

**Comment by kcollins-ene** [comment]
Bill, I think I've run across this issue recently myself--the reports only render with little square boxes?  I'll look into adding those packages and see if I can get that tidied up.  Thanks for the report!

**Comment by bgreat** [comment]
For this case, there is a gateway exception that indicates there is an inability to match a font request to an stalled font.

java.lang.ClassCastException: class sun.font.CompositeFont cannot be cast to class sun.font.PhysicalFont

I did some more checking and the packages missing versus the 7.9 image seem to be fontconfig and fonts-dejavu. I think that is a minimum requirement for fonts. For reliable rendering of some font families it would be good to be able to add some other packages. I'm still looking to identify a minimum set for reliable rendering. One issue is doing design on Windows and then running reports on a Linux gateway. Fonts will be mapped where possible by family, but some fonts do not map well.

**Comment by bgreat** [comment]
Adding fontconfig and fonts-dejavu to the installed packages resolved the exception issue. I can generate scheduled reports now. I'll leave it to you to update the Dockerfile.

Enjoy!

**Comment by thirdgen88** [comment]
Closing this out, updated per @bgreat suggestions in commit c61b698.  Thanks again!
