### ISSUE TITLE
Is there any planned support for armhf/64?

### ISSUE THREAD

**Issue by AaronAutomation** [thirdgen88/ignition-docker#11]
Just curious if there is planned support for the armhf release or even arm64?

**Comment by thirdgen88** [comment]
Yes!!!  I’ve got to get the details figured out in order to have it be seamless (via the manifest files/etc) and not be offered by a separate tag.  I also have to get the cross-architecture builds figured out too.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thirdgen88** [comment]
Finally getting around to this, should be coming soon.  Ignition only releases for armhf, so that and amd64 (current) will be where we start.  👍

**Comment by thirdgen88** [comment]
`nightly` builds are multi-arch (armhf and amd64), coming soon to `master`!

**Comment by thirdgen88** [comment]
I should have squashed all the commits I brought over from nightly, but this is now live on the latest 8.0.13 image!  See the docs section on [Multi-Architecture Builds](https://github.com/thirdgen88/ignition-docker/tree/master/docs#multi-architecture-builds) for more detailed information.
