### ISSUE TITLE
Image ignition-8.0.6-synology

### ISSUE THREAD

**Issue by proartsrl** [thirdgen88/ignition-docker#12]
I have been testing this image for a while but it allways gives those messages on startup and then stop.

"Provisioning will be logged here: /usr/local/share/ignition/logs/provisioning.log"
"Waiting for commissioning servlet to become active..."
"Failed to detect RUNNING status during Commissioning Phase after 10 delay."

This is the first time i see something like this.

What can i do?

Thanks in advance.

**Comment by thirdgen88** [comment]
I did add a couple more customizable environment variables to the image.  You should be able to set `IGNITION_COMMISSIONING_DELAY` to something higher if the container is slow to start (perhaps due to constrained hardware or other system load issues).  10 seconds was an arbitrary pick after observing typical behavior where that commissioning servlet would be online almost immediately.

**Comment by proartsrl** [comment]
I have tested the canonical 8.0.6 and, as all the others images that I use, starts like a charm. Problem arise only with "synology" version.

Here the registry of "synology" version with  IGNITION_COMMISSIONING_DELAY = 60:

"Added Init Setting SystemName=ignition"
"Gateway Restore Options: --name ignition"
"Provisioning will be logged here: /usr/local/share/ignition/logs/provisioning.log"
"Waiting for commissioning servlet to become active..."

Then after 60 seconds it stops.


Here the "beginning" part of the registry of the canonical 8.0.6:

"wrapper  | --> Wrapper Started as Console"
"]0;Ignition Gatewaywrapper  | Java Service Wrapper Standard Edition 64-bit 3.5"
"wrapper  |   Copyright (C) 1999-2018 Tanuki Software, Ltd. All Rights Reserved."
"wrapper  |     http://wrapper.tanukisoftware.com"
"wrapper  |   Licensed to Inductive Automation for Inductive Automation"
"wrapper  | "
"wrapper  | Launching a JVM..."
"jvm 1    | WrapperManager: Initializing..."
"jvm 1    | 05:33:35,726 |-INFO in ch.qos.logback.classic.LoggerContext[default] - ...."

and so on. It start very quickly.

**Comment by thirdgen88** [comment]
Can you provide the full `docker run` command you are using?  The other thing that would be useful to see would be to `docker cp` the provisioning.log from inside the failed container instance.  Inspecting that log might provide some clues—it looks like something is causing things to stall/halt, not a matter of waiting long enough.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by proartsrl** [comment]
Sorry, no i cannot. I am using an app on board of a Synology NAS that shell every complexity in a nice and easy gui interface.
Some diagnostic is made through a registry and is what I was sending you.

I'am so confident with your container that I am using it (8.0.2 version on a couple of Synology NAS RS3617xs connected in High Availability and MariaDB database) since 6 months in a production environment without a glitch. Unfortunately not using any external volume due the limitation of UID and GID I mentioned.

What i can do easily is giving you a direct browser connection to a small Synology NAS with all the necessary containers already installer ready to be launched to see the problems.

Just give me a check. Synology Docker APP Interface is very easy to manage, no instruction required.
(Hope you understand my broken english.)

**Comment by proartsrl** [comment]
One more info.
I am now able to run 8.0.6 synology image.
But when i try to map a volume ("/docker" volume on synology  mapped to "/var/lib/ignition/data") as stated on you web page, conainer does not stat with this error
"/usr/local/bin/docker-entrypoint.sh: line 289: /usr/local/share/ignition/data/.docker-init-complete: Permission denied"
But i am sure that UID and GID are correct: 1024 and 100 checked via SSH on synology.

Thanks in advance.

**Comment by thirdgen88** [comment]
@proartsrl, I took a look at this and it circles back to trying to use a bind-mount to preserve the gateway data instead of a docker volume mount.  The error in the provisioning log is below:

```
FATAL  | wrapper  | Unable to open configuration file: data/ignition.conf (No such file or directory)
FATAL  | wrapper  |   Current working directory: /usr/local/share/ignition
FATAL  | wrapper  |   The Wrapper will stop.
```

When you bind-mount a path into place within a container, it supersedes the information within that location.  This is why the base `data/ignition.conf` is not there when Ignition tries to launch in your configuration.  Using a [standard docker volume](https://github.com/thirdgen88/ignition-docker/tree/master/docs#how-to-persist-gateway-data) will inherit the files in that location and then continue to preserve them.  Perhaps if I could get a view of this Synology Docker App interface I could help more.  Feel free to e-mail me if you can provide that test connection.

**Comment by proartsrl** [comment]
You are right, I understand now, not UID or GUID.

"This is why the base data/ignition.conf is not there when Ignition tries to launch in your configuration"

But in synology interface I can bind-mount only local path, not docker volumes (I cannot even create one!) and usually this works, probably because dir are empty at the begining and all files are created afterward.

I tested a container on synology (Transmission), just to be sure,  that bind-mount 2 path on /config and /downloads and it worked at first glance.
And to be "more" sure I installed an ubuntu PC and tested your container bind-mounting it on a local path and have had the same result, while, as per your advice, using a volume worked like a charm.

So I am stuck once again if there is no possibility to create data/ignition.conf after the bind-mount of a local path.
Problem understood. Now it's up to you and your kindness investigate for a solution.

Anyway I tank you for your effort till now

**Comment by thirdgen88** [comment]
@proartsrl, just thought I'd mention that you can now use my image (starting with the `8.1` tag) directly on your Synology with volume persistence.  All you have to do is target `/data` as your mount point within the container, and then also adjust your ownership of the volume directory on your Synology (via SSH) to `999:999`.

**Comment by proartsrl** [comment]
Dear Kevin
first of all I thank you for your precious work.

I am using "all" your versions starting from 7.9, not just 8.1, on
Synology's NAS. They are reliable, cheap, MariaDB runs natively, at the
only cost of adding a twin hardware they allow redundancy.

There remains a problem with Synology, not solved, but for which I found a
trick.
When creating the container I cannot associate the / var / lib / ignition /
data folder with a folder on the NAS because the installation crashes.
My solution is:
1) install the container without associating the volume, and let it finish
the installation correctly
2) turn off and associate a NAS directory with a temporary container folder
on the NAS
3) using the container terminal, copy the contents of / var / lib /
ignition / data in the temporary volume supported by the NAS folder.
4) turn off the container and associate the this NAS folder to / var / lib
/ ignition / data.

From this moment the container will work by relying on the NAS folder.

Thanks again.

Marco Barbieri
engineer
Proart Srl

Via Paolucci de' Calboli 28
I-26100 CREMONA - ITALY
Phone:     +39-0372-32054
e-mail:     marco.barbieri@proartsrl.org

Think to the environment before printing this document

**** Riservatezza / Confidentiality ****
In ottemperanza al D.L. n. 196 del 30/6/2003 in materia di protezione dei
dati personali, le informazioni contenute in questo messaggio sono
strettamente riservate ed esclusivamente indirizzate al destinatario
indicato (oppure alla persona responsabile di rimetterlo al destinatario).
Vogliate tener presente che qualsiasi uso, riproduzione o divulgazione di
questo messaggio e vietato. Nel caso in cui aveste ricevuto questo
messaggio per errore, vogliate cortesemente avvertire il mittente e
distruggere il presente messaggio.

According to Italian law D.L. 196/2003 concerning privacy, if you are not
the addressee (or responsible for delivery of the message to such person)
you are hereby notified that any disclosure, reproduction, distribution or
other dissemination or use of this communication is strictly prohibited. If
you have received this message in error, please destroy it and notify us by
email


Il giorno lun 23 nov 2020 alle ore 03:33 Kevin Collins <
notifications@github.com> ha scritto:

**Comment by proartsrl** [comment]
Dear Kevin.
I am grateful and impressed for your commitment and passion.
I ask you for information for your experience.

I need to print from your container (ignition 8.1.3) to a network
printer and I have no idea how to do it. I read that I could use
preconfigured containers with CUPS installed but I have no idea how to
reach the container from your image. I have read about installing
cups-client in the container but I need your kindness and detailed
instructions.

I thank you in advance.


Marco Barbieri
engineer
Proart Srl

Via Paolucci de' Calboli 28
I-26100 CREMONA - ITALY
Phone:     +39-0372-32054
e-mail:     ***@***.***

Think to the environment before printing this document

**** Riservatezza / Confidentiality ****
In ottemperanza al D.L. n. 196 del 30/6/2003 in materia di protezione dei
dati personali, le informazioni contenute in questo messaggio sono
strettamente riservate ed esclusivamente indirizzate al destinatario
indicato (oppure alla persona responsabile di rimetterlo al destinatario).
Vogliate tener presente che qualsiasi uso, riproduzione o divulgazione di
questo messaggio e vietato. Nel caso in cui aveste ricevuto questo
messaggio per errore, vogliate cortesemente avvertire il mittente e
distruggere il presente messaggio.

According to Italian law D.L. 196/2003 concerning privacy, if you are not
the addressee (or responsible for delivery of the message to such person)
you are hereby notified that any disclosure, reproduction, distribution or
other dissemination or use of this communication is strictly prohibited. If
you have received this message in error, please destroy it and notify us by
email


Il giorno lun 23 nov 2020 alle ore 10:51 Marco Barbieri <
***@***.***> ha scritto:
