### ISSUE TITLE
Modules Paths

### ISSUE THREAD

**Issue by kreddad** [thirdgen88/ignition-docker#128]
I have modules paths -v /path/to/my/modules:/modules \ , but every time installing modules don't go to this path. and also evetime do changes to Kcollins/ignition docker, I have to install the modules evetime . any advice
thank you

**Comment by thirdgen88** [comment]
Take a look at the documentation [here](https://github.com/thirdgen88/ignition-docker/tree/main/docs#how-to-integrate-third-party-modules).  The way it works is you place your third-party modules in the folder on the host; then, they sym-link into place prior to gateway startup.  You can't manage them via the gateway webpage.  To control which of the built-in modules are loaded, look at the `GATEWAY_MODULES_ENABLED` environment variable in the docs.

**Comment by kreddad** [comment]
GATEWAY_MODULES_ENABLED=all, and copied modules.modI to -v /path/to/my/modules then worked'
thanks again
