### ISSUE TITLE
Install Ignition without including all inductive modules

### ISSUE THREAD

**Issue by nslocum** [thirdgen88/ignition-docker#15]
Currently, the Dockerfile installs Ignition along with all Inductive modules. Do you know of a way to selectively install only the modules I want?

The docs don't specify a way:
https://docs.inductiveautomation.com/display/DOC79/Linux+-+Install

https://github.com/thirdgen88/ignition-docker/blob/60e8295fbdc5fad9d3de4fcba8888b2434a956f9/7.9/Dockerfile#L31

**Comment by nslocum** [comment]
I ended up adding commands to the `Dockerfile` to remove the modules. This code can be placed after the `RUN` command which downloads and installs ignition.

```docker
WORKDIR /var/lib/ignition/user-lib/modules
RUN rm "User Manual-module.modl" && \
	rm "DNP3-Driver.modl" && \
	rm "Mobile-module.modl" && \
	rm "Omron-Driver.modl" && \
	rm "SFC-module.modl" && \
	rm "Siemens Drivers-module.modl" && \
	rm "SMS Notification-module.modl"
```

**Comment by thirdgen88** [comment]
This is something I'm planning to integrate into the base Dockerfile.  Right now I'm planning on moving all of the modules out of the default location and then conditionally sym-linking them into place.  Default behavior will be to include them all, but I'll expose environment variables to disable/enable the default modules.  Welcome to other thoughts on how this should be done or what other features might be useful.

**Comment by thirdgen88** [comment]
This functionality is now built into the image as of the latest push of 7.9.14 and 8.0.13.  Information on how to use it is located in the Docker Hub [README](https://github.com/thirdgen88/ignition-docker/tree/master/docs), specifically this section [here](https://github.com/thirdgen88/ignition-docker/tree/master/docs#how-to-enabledisable-default-modules).  @nslocum, feel free to check it out and see if it makes your life a little easier!  Feedback welcomed, too.
