### ISSUE TITLE
Install using .run vs .zip

### ISSUE THREAD

**Issue by nslocum** [thirdgen88/ignition-docker#16]
@thirdgen88 Can you help me understand why the 7.9 Dockerfile installs Ignition using the prepackaged `.run` installer while 8.0 uses the `.zip` archive?

I'm curious because using the zip archive seems like a simpler approach. I'm considering reworking the 7.9 code to use the zip. But, I'm not that familiar with Ignition so I'm most certainly overlooking important details. 

Btw, your repo is *really* well done, the code is clear and concise and so is the documentation. Thanks for sharing your work! You clearly put a lot of thought into it.

**Comment by thirdgen88** [comment]
@nslocum The primary reason for moving to the Zip installer was actually that Ignition Edge is no longer part of the installer—it is only available as the zip package.  I still follow some of the traditional file system location conventions (from the .run installer) for backwards compatibility (and so things are placed nicely).
I’m glad you’re enjoying the image, it is good to hear from folks that are leveraging it!  😎

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nslocum** [comment]
That makes sense. Thanks for explaining it, and thanks again for sharing your great work! 😄
