### ISSUE TITLE
Scheduled Backup Path

### ISSUE THREAD

**Issue by sjai013** [thirdgen88/ignition-docker#17]
Hi,

First, thanks for this!  This is absolutely wonderful.

Is there any way to automatically configure a binding for scheduled backup path?  
My particular use-case is with the Ignition-MySQL example.  I tried modifying the docker-compose.yml file for the gateway section:

e.g.
```
   volumes:
      - ./gateway_backup.gwbk:/restore.gwbk
      - gateway_data:/var/lib/ignition
      - ./backups:/home/ignition/backups # Backup line
```

but I got access errors, because the gateway container did not have write access to that path.  I was able to get it going by executing a command as root:
```
docker exec -u 0 -it 6ac2124cdbb2  bash -c "mkdir /home/ignition/backups; chown ignition /home/ignition/backups"
```

I was wondering if there was a better way to do this?  Happy to submit a PR for the Dockerfile (although I have very little experience).

**Comment by thirdgen88** [comment]
What you're doing should work fine under Docker for Windows or Docker for Mac, however if you're on Linux directly, the permissions on that `./backups` folder definitely matter.  If, from your host, you perform the following, you should have no access issues:

```
$ chown 999.999 ./backups
$ chmod 660 ./backups
```

If you look at [these lines](https://github.com/thirdgen88/ignition-docker/blob/a92191008477fc956a5a5a2dc198abd75dcc02b4/8.0/Dockerfile#L56-L59) from the Dockerfile, you'll see that within the container, Ignition is running as a user/group called `ignition` with a default UID/GID of 999.

Alternatively, you can build the image yourself and specify, using those build arguments, custom UID/GID to match your environment.

Let me know if any of this guidance helps you get going more smoothly.  Thank you for taking the time to reach out!

**Comment by sjai013** [comment]
Thanks for your help.  I haven't been able to test on a Linux machine, but the end machine is Windows, so mapping the volume just works, as you mention.
