### ISSUE TITLE
Healthcheck needs a curl timeout

### ISSUE THREAD

**Issue by ptrdlbrg** [thirdgen88/ignition-docker#20]
I was running an Ignition container and at some point the Ignition web server went unresponsive (I assume it is nothing to do with your docker image). When I checked the processes running on the server, I saw several thousand `curl` and `grep` processes. These were the `curl` and `grep` processes from the health check. The `curl` command doesn't have a default timeout so it was hanging indefinitely because the Ignition server didn't send a response. The `grep` was waiting for `curl` to complete before it stopped.

This build-up of previous health check processes could be avoided by using the `--max-time` option in `curl` and setting it less than or equal to the HEALTHCHECK `--timeout` value.

Thanks again for your work!

**Comment by thirdgen88** [comment]
@ptrdlbrg, good catch, I guess I hadn’t stuck my nose in a container that was “unhealthy” to see those stuck processes.  I’ll definitely get this added in!  Thank you!
