### ISSUE TITLE
Container gives 'Gateway Not Running' for latest image. SQL Exception 

### ISSUE THREAD

**Issue by richhl** [thirdgen88/ignition-docker#21]
To reproduce launch latest ignition container with the command:

`>$ docker run -p 8088:8088 --name my-ignition -e GATEWAY_ADMIN_PASSWORD=****** -d kcollins/ignition
`
Gateway not running message in localhost:8088. container log:

`jvm 1    | I [P.InternalDatabase            ] [15:28:45]: Looking for existing internal database "config.idb"... 
jvm 1    | I [P.InternalDatabase            ] [15:28:45]: ... found existing. 
jvm 1    | I [g.InternalDatabaseManager     ] [15:28:45]: Upgrading schema for module "ignition" 
jvm 1    | I [o.e.j.s.h.ContextHandler      ] [15:28:45]: Started c.i.c.MainWebAppContext@26e6a384{Ignition,/,file:///usr/local/share/ignition/webserver/webapps/main/,AVAILABLE} 
jvm 1    | W [g.InternalDatabaseManager     ] [15:28:45]: Error executing: INSERT OR IGNORE INTO SEQUENCES(name, val, srctable) VALUES ('STOREANDFORWARDSYSSETTINGS_SEQ', 0, 'STOREANDFORWARDSYSSETTINGS') 
jvm 1    | W [P.InternalDatabase            ] [15:28:45]: Unable to connect to internal database "config.idb", shutting down... 
jvm 1    | W [P.InternalDatabase            ] [15:28:45]: Unable to restore from autobackups because none were found. 
jvm 1    | E [P.InternalDatabase            ] [15:28:45]: Startup of internal database "config.idb" failed, autobackups disabled. 
jvm 1    | org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: SEQUENCES)
jvm 1    | 	at org.sqlite.core.DB.newSQLException(DB.java:909)
jvm 1    | 	at org.sqlite.core.DB.newSQLException(DB.java:921)
jvm 1    | 	at org.sqlite.core.DB.throwex(DB.java:886)
jvm 1    | 	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
jvm 1    | 	at org.sqlite.core.NativeDB._exec(NativeDB.java:87)
jvm 1    | 	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:116)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.AbstractDBInterface.runUpdateQuery(AbstractDBInterface.java:222)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.LocalDBManagerImpl$SingleConnectionDBInterface.runUpdateQuery(LocalDBManagerImpl.java:748)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.LocalDBManagerImpl.updatePersistentRecords(LocalDBManagerImpl.java:556)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.LocalDBManagerImpl$SQLiteSettingsDBManager.onConnected(LocalDBManagerImpl.java:921)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.sqlite.SQLiteDBManager.startupInternal(SQLiteDBManager.java:318)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.sqlite.SQLiteDBManager.startup(SQLiteDBManager.java:202)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.LocalDBManagerImpl.setup(LocalDBManagerImpl.java:176)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.IgnitionGateway.startupInternal(IgnitionGateway.java:830)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.redundancy.RedundancyManagerImpl.startup(RedundancyManagerImpl.java:283)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.IgnitionGateway.initRedundancy(IgnitionGateway.java:697)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.IgnitionGateway.lambda$initInternal$0(IgnitionGateway.java:635)
jvm 1    | 	at com.inductiveautomation.ignition.common.execution.impl.BasicExecutionEngine$ThrowableCatchingRunnable.run(BasicExecutionEngine.java:518)
jvm 1    | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
jvm 1    | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
jvm 1    | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
jvm 1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jvm 1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jvm 1    | 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | I [g.InternalDatabaseManager     ] [15:28:45]: DBManager shutting down (immediate)... 
jvm 1    | I [g.InternalDatabaseManager     ] [15:28:45]: DBManager shut down in 0ms 
jvm 1    | E [IgnitionGateway               ] [15:28:45]: Error during context startup. 
jvm 1    | com.inductiveautomation.ignition.gateway.localdb.DBStartupException: Error loading internal database "config.idb"
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.sqlite.SQLiteDBManager.startup(SQLiteDBManager.java:254)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.LocalDBManagerImpl.setup(LocalDBManagerImpl.java:176)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.IgnitionGateway.startupInternal(IgnitionGateway.java:830)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.redundancy.RedundancyManagerImpl.startup(RedundancyManagerImpl.java:283)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.IgnitionGateway.initRedundancy(IgnitionGateway.java:697)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.IgnitionGateway.lambda$initInternal$0(IgnitionGateway.java:635)
jvm 1    | 	at com.inductiveautomation.ignition.common.execution.impl.BasicExecutionEngine$ThrowableCatchingRunnable.run(BasicExecutionEngine.java:518)
jvm 1    | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
jvm 1    | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
jvm 1    | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
jvm 1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jvm 1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jvm 1    | 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: SEQUENCES)
jvm 1    | 	at org.sqlite.core.DB.newSQLException(DB.java:909)
jvm 1    | 	at org.sqlite.core.DB.newSQLException(DB.java:921)
jvm 1    | 	at org.sqlite.core.DB.throwex(DB.java:886)
jvm 1    | 	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
jvm 1    | 	at org.sqlite.core.NativeDB._exec(NativeDB.java:87)
jvm 1    | 	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:116)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.AbstractDBInterface.runUpdateQuery(AbstractDBInterface.java:222)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.LocalDBManagerImpl$SingleConnectionDBInterface.runUpdateQuery(LocalDBManagerImpl.java:748)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.LocalDBManagerImpl.updatePersistentRecords(LocalDBManagerImpl.java:556)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.LocalDBManagerImpl$SQLiteSettingsDBManager.onConnected(LocalDBManagerImpl.java:921)
jvm 1    | 	at com.inductiveautomation.ignition.gateway.localdb.sqlite.SQLiteDBManager.startupInternal(SQLiteDBManager.java:318)
rich@Ideapad330:~$ A
`

**Comment by thirdgen88** [comment]
Interesting..  I just tried a local spool-up on a Windows machine with the same basic `docker run` that you list below (the machine I tested on didn’t have the latest image either and thusly pulled it fresh) and did not encounter these errors—got a running gateway like expected..  I’ll cross-check on a couple of other platforms here as well.  Can you provide some additional details on your environment?  If you’re on Windows or macOS, can you also share some of the settings of your Docker Desktop setup (CPU core count, RAM allocation, etc)?

**Comment by thirdgen88** [comment]
@richhl, I also just spooled up a fresh Ubuntu+Docker VM and was able to get the latest image to launch just fine there as well.  I'd be interested in the output from the following commands too (my Ubuntu VM shown here in the example output):

#### Docker Version
```
ubuntu@focal-docker-test:~$ docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

#### Docker Image List (this `latest` tag here should be the `8.0.12` version at time of writing)
```
ubuntu@focal-docker-test:~$ docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
kcollins/ignition   latest              7be0cfdd5873        3 weeks ago         1.17GB
```

**Comment by richhl** [comment]
thx @thirdgen88

Here you are:

$>cat /etc/debian_version
9.6

$>uname -a
Linux Ideapad330 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64
GNU/Linux

$>docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$> docker image ls

REPOSITORY                             TAG                 IMAGE ID
   CREATED             SIZE
bkimminich/juice-shop                  latest              ea6d680b6b59
   10 days ago         338MB
674b24d03614fde205a38f449800857a_www   latest              9b63feedec9a
   2 weeks ago         378MB
kcollins/ignition                      latest              7be0cfdd5873
   3 weeks ago         1.17GB
....

$> docker run -p 8088:8088 --name my-ignition -e
GATEWAY_ADMIN_PASSWORD=****** -d kcollins/ignition:tag

fails....complete wrapper.log attached.
___________________________

Richard C. Hidalgo Lorite
Director de Sistemas
ISI Argonauta, S.L.
C/Alcalá 196, apto. 13, 28028 Madrid
Telf: +34 691 502 235
http://www.argonauta.org

**Comment by richhl** [comment]
it has worked at next launch.

$>docker rm -f my-ignition

Launched again with same command and it has worked......
