### ISSUE TITLE
JSON escaping values sent during auto-commissioning

### ISSUE THREAD

**Issue by ptrdlbrg** [thirdgen88/ignition-docker#29]
During the auto-commissioning procedure in the `docker-entrypoint.sh` for Ignition 8.0, some JSON values are constructed and then sent to Ignition via `curl`. Some variable values are inserted literally into the JSON without first escaping them according to the rules for JSON strings. Backslashes, double quotes, and control characters (U+0000 through U+001F) need to be escaped with a backslash when they're in a JSON string. Without proper escaping, some variable values can cause the JSON to be invalid and unable to be parsed.

For example, when I set a GATEWAY_ADMIN_USERNAME to a value including a double quote, I got an error like this:
```
Provisioning will be logged here: /usr/local/share/ignition/logs/provisioning.log
Waiting for commissioning servlet to become active...
Performing commissioning actions...
  IGNITION_EDITION: full
  EULA_STATUS: accepted
ERROR: Unexpected Response (400) during Commissioning phase: Configuring Authentication
HTTP/1.1 400 Bad Request
Referrer-Policy: strict-origin-when-cross-origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 410

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 400 Malformed body sent</title>
</head>
<body><h2>HTTP ERROR 400 Malformed body sent</h2>
<table>
<tr><th>URI:</th><td>/post-step</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Malformed body sent</td></tr>
<tr><th>SERVLET:</th><td>CommissioningServlet</td></tr>
</table>

</body>
</html>
```

People generally won't have usernames with double quotes, backslashes, tabs, or newlines in them, but some might. Or they might do it by accident. Ideally they'd see an error about the invalid value they specified, rather than a generic error caused by failure to parse JSON. 

There are very limited ways for this to cause real trouble (right now).  I wanted to make this JSON-escaping issue known in case more commissioning steps are added in the future and there are more opportunities for trouble.

If you're looking for a good way to construct your JSON in a bash script that will allow you to fix this issue, I'd recommend using the excellent [jq](https://stedolan.github.io/jq/) command line tool. For this container you can use `apt` to get it. The `jq` command and its dependencies weigh in at about 1MB. You can provide your variable values as arguments (Search for `--arg` in the [jq manual](https://stedolan.github.io/jq/manual/). If you're interested then I can leave an example of how `jq` could be used.

As an aside, currently you _can_ have a username with a double quote, backslash, and other odd characters in it right now because of a bug in the commissioning process. I reported it in the Ignition forums: https://forum.inductiveautomation.com/t/bug-16714-no-username-validation-in-commissioning/36164

**Comment by ptrdlbrg** [comment]
Here's an example of how `jq` could be used to fix the escaping issue.  In the line below, the `${auth_user}` and `${auth_password}` should each be escaped.
```
local auth_payload='{"id":"authentication","step":"authSetup","data":{"username":"'${auth_user}'","password":"'${auth_password}'"}}'
```
You can construct the complete object via the `jq` object construction synax:
```
local auth_payload=$(jq -ncM --arg user "$auth_user" --arg pass "$auth_password" '{ id: "authentication", step:"authSetup", data: {username: $user, password: $pass}}')
```

**Comment by thirdgen88** [comment]
Thank you @ptrdlbrg for the feedback, I think your suggestions are on-point and integrating them worked wonderfully.
