### ISSUE TITLE
Gateway from 7.9.16 tag does not start

### ISSUE THREAD

**Issue by kevinherron** [thirdgen88/ignition-docker#38]
It seems we released 7.9.16, at least the zip distributions, with an ignition.conf that has an absolute rather than relative `wrapper.java.library.path` value:

```
# Java Library Path (location of Wrapper.DLL or libwrapper.so)
wrapper.java.library.path.1=/usr/local/bin/ignition/lib
```

Ignition in a container based on the 7.9.16 image fails to start with this error:
```
Starting Ignition Gateway...
wrapper | --> Wrapper Started as Console
]0;Ignition Gatewaywrapper | Java Service Wrapper Standard Edition 64-bit 3.5.35
wrapper | Copyright (C) 1999-2018 Tanuki Software, Ltd. All Rights Reserved.
wrapper | http://wrapper.tanukisoftware.com
wrapper | Licensed to Inductive Automation for Inductive Automation
wrapper |
wrapper | Launching a JVM...
jvm 1 | WrapperManager: Initializing...
jvm 1 | WrapperManager:
jvm 1 | WrapperManager: ERROR - Unable to load the Wrapper's native library because none of the
jvm 1 | WrapperManager: following files:
jvm 1 | WrapperManager: libwrapper-linux-x86-64.so
jvm 1 | WrapperManager: libwrapper.so
jvm 1 | WrapperManager: could be located on the following java.library.path:
jvm 1 | WrapperManager: /usr/local/bin/ignition/lib
jvm 1 | WrapperManager: Please see the documentation for the wrapper.java.library.path
jvm 1 | WrapperManager: configuration property.
jvm 1 | WrapperManager:
wrapper | <-- Wrapper Stopped
```

Presumably because the image uses `/usr/local/share/ignition` as its Ignition install directory.

I _think_ we've got this fixed for a future 7.9.17 release, but that leaves 7.9.16 in a bit of a broken spot here.

**Comment by thirdgen88** [comment]
@kevinherron, excellent catch..  I'll admit, I updated everything for 7.9.15 and didn't expect a 7.9.16 so soon thereafter.  I should have spooled it up at least!  All the more encouragement to follow-through with issue #27.  

I'll get this corrected and push an updated image for 7.9.16.  Thanks again for the heads up!

**Comment by kevinherron** [comment]
Yeah... 7.9.15 contained a nasty bug that required a quick 7.9.16 follow up release containing only that fix. I'm not sure how the broken paths ended up in there too. 

While still available from S3 we've actually pulled 7.9.15 from the downloads section of the website. I don't know if you can do the same with your 7.9.15 image but it may be worth doing so if you can.

**Comment by thirdgen88** [comment]
Okay, the latest 7.9.16 image is now happy.  👍

**Comment by kevinherron** [comment]
Thanks! I almost PR'd something similar but wasn't sure how you'd want to fix this. 

We briefly discussed uploading new zip files with just the conf files corrected but no decision has been made yet.

**Comment by thirdgen88** [comment]
Ultimately, I think the update that was made is probably a correct (and irrespectively useful) one, as those particular settings need to be tailored to the particular installation locations.  So the entry point will take care of updating those settings when the container is launched fresh (of course, existing ignition.conf in preserved volumes will remain un-touched).

FYI, I did delete the 7.9.15 tags against kcollins/ignition on Docker Hub, so hopefully that will prevent folks from inadvertently drawing that release in the future..
