### ISSUE TITLE
Named volume against `/data` results in permissions error

### ISSUE THREAD

**Issue by thirdgen88** [thirdgen88/ignition-docker#44]
In Docker Desktop for macOS, attempting to use a named volume against `/data` (versus the standard `/var/lib/ignition/data`) results in:

```bash
/usr/local/bin/docker-entrypoint.sh: line 418: /data/.docker-init-complete: Permission denied
```

... since `/data` ends up with _root.root_ ownership.  Consider implementing use of gosu to enable a step-down from root user instead of running the entire entrypoint as `ignition` UID/GID.

**Comment by scottdkey** [comment]
Hey -- it seems like any of your mapped aliases result in a permissions error. Going through the docker it just seems like the ignition user doesn't have permissions for those paths.

I haven't had time to go through the dockerfile, but I think the solution would just be to do a 

`chown +x {folderPath}` 

as part of the build process. Moving this weekend, gonna try to create a pull request when I have time. If you get there first I wouldn't be mad about it.

**Comment by thirdgen88** [comment]
Currently `/data` doesn't exist within the build, and in the entrypoint its existence is what triggers seeding that location with the original files from `/var/lib/ignition/data` and then relinking everything.  I could include `/data` in the image and assign the appropriate permissions (like I do for everything else), then use a more explicit detection of a mount (like what I do for the double-mount detection [here](https://github.com/thirdgen88/ignition-docker/blob/631a1d76bc2e0861b538cdeec486af1be747d9cc/8.1/docker-entrypoint.sh#L409-L415)) to define `DATA_VOLUME_LOCATION`.  This would ensure that the base permissions are set appropriately...
