### ISSUE TITLE
JVM Startup Failed - Edge Running on Wago PFC200 (arm32)

### ISSUE THREAD

**Issue by willchomyc** [thirdgen88/ignition-docker#56]
I am trying to get Ignition Edge running on a Wago PFC200 using docker. I initially had the issue from this thread: https://forum.inductiveautomation.com/t/docker-container-does-not-start/43915

Which has now been partially remedied (no more nanosleep errors and the container makes it past starting), however I am still having an issue with the JVM wrapper not responding. The container now remains running but with the (unhealthy) status and the gateway still doesn't respond.

**run command:**
docker run -p 8088:8088 --privileged  --name my-ignition-edge -e GATEWAY_ADMIN_PASSWORD=password -e IGNITION_EDITION=edge -d kcollins/ignition:latest

**logs:**
init     | Starting Ignition Gateway...
init     | Initiating commissioning helper functions...
wrapper  | 2021/04/14 00:42:04 | --> Wrapper Started as Console
wrapper  | 2021/04/14 00:42:04 | Java Service Wrapper Standard Edition 32-bit 3.                                                                                                                                                             5.42
wrapper  | 2021/04/14 00:42:04 |   Copyright (C) 1999-2020 Tanuki Software, Ltd.                                                                                                                                                              All Rights Reserved.
wrapper  | 2021/04/14 00:42:04 |     http://wrapper.tanukisoftware.com
wrapper  | 2021/04/14 00:42:04 |   Licensed to Inductive Automation for Inductiv                                                                                                                                                             e Automation
wrapper  | 2021/04/14 00:42:04 |
wrapper  | 2021/04/14 00:42:09 | Launching a JVM...
jvm 1    | 2021/04/14 00:42:19 | WrapperManager: Initializing...
wrapper  | 2021/04/14 00:42:39 | Startup failed: Timed out waiting for a signal                                                                                                                                                              from the JVM.
wrapper  | 2021/04/14 00:42:40 | JVM did not exit on request, termination reques                                                                                                                                                             ted.
wrapper  | 2021/04/14 00:42:40 | JVM received a signal SIGKILL (9).
wrapper  | 2021/04/14 00:42:40 | JVM process is gone.
wrapper  | 2021/04/14 00:42:40 | JVM exited after being requested to terminate.
wrapper  | 2021/04/14 00:42:45 | Reloading Wrapper configuration...
wrapper  | 2021/04/14 00:42:50 | JVM process is gone.
wrapper  | 2021/04/14 00:42:50 | Launching a JVM...
jvm 2    | 2021/04/14 00:42:59 | WrapperManager: Initializing...
wrapper  | 2021/04/14 00:43:20 | Startup failed: Timed out waiting for a signal                                                                                                                                                              from the JVM.
wrapper  | 2021/04/14 00:43:20 | JVM did not exit on request, termination reques                                                                                                                                                             ted.
wrapper  | 2021/04/14 00:43:20 | JVM received a signal SIGKILL (9).
wrapper  | 2021/04/14 00:43:20 | JVM process is gone.
wrapper  | 2021/04/14 00:43:20 | JVM exited after being requested to terminate.
wrapper  | 2021/04/14 00:43:26 | Reloading Wrapper configuration...
wrapper  | 2021/04/14 00:43:29 | JVM process is gone.
wrapper  | 2021/04/14 00:43:29 | Launching a JVM...
jvm 3    | 2021/04/14 00:43:38 | WrapperManager: Initializing...
wrapper  | 2021/04/14 00:43:59 | Startup failed: Timed out waiting for a signal                                                                                                                                                              from the JVM.
wrapper  | 2021/04/14 00:43:59 | JVM did not exit on request, termination reques                                                                                                                                                             ted.
wrapper  | 2021/04/14 00:44:00 | JVM received a signal SIGKILL (9).
wrapper  | 2021/04/14 00:44:00 | JVM process is gone.
wrapper  | 2021/04/14 00:44:00 | JVM exited after being requested to terminate.
wrapper  | 2021/04/14 00:44:05 | Reloading Wrapper configuration...
wrapper  | 2021/04/14 00:44:08 | JVM process is gone.
wrapper  | 2021/04/14 00:44:08 | Launching a JVM...

**Comment by thirdgen88** [comment]
I did a quick search on Wago PFC200 and came up with [this website](https://www.wago.com/us/pfc200) which seems to indicate that the device (Gen 2) has a maximum RAM allocation of 512MB (looks like some of the earlier models even had 256MB).  You're going to be very memory-constrained on the 512MB model--Ignition won't be feasible at all on the 256MB RAM model (output of `free` or `cat /proc/meminfo` would tell you).  I just took a look at the entrypoint script and it looks like the environment variables `GATEWAY_INIT_MEMORY` and `GATEWAY_MAX_MEMORY` that I have for driving the memory allocation enforces max memory at >=512MB..  Thankfully, as of `kcollins/ignition:8.1.4`, you can actually feed JVM/wrapper args directly through the _command_ options on your container run, e.g.:

```bash
$ docker run -d -p 8088:8088 --privileged --name my-ignition-edge \
    -e GATEWAY_ADMIN_PASSWORD=password \
    -e IGNITION_EDITION=edge \
    kcollins/ignition:8.1.4 \
    wrapper.java.initmemory=256 \
    wrapper.java.maxmemory=384
```

I'd try the above first, just to see if you can get any further in the launch--it looks like, based on your logs, that the JVM probably isn't able to allocate the required default amount of memory (init of 256M, max of 1024M).

**Comment by willchomyc** [comment]
That did the trick, thanks a lot for the quick reply.
I had to dial them back to 200 and 250 but that got the container to at least stop choking. However I couldn't get past the "gateway starting" webpage, pretty sure it's a memory/resource issue. I do have the 512MB model and was doing this mostly to see if it was possible, since I am drawn to Ignition's ability to buffer MQTT messages on the sender when the broker connection is unreliable. However it seems it isn't a realistic application for the PFC200.
