### ISSUE TITLE
Problem with mounting volumes

### ISSUE THREAD

**Issue by proartsrl** [thirdgen88/ignition-docker#6]
I am trying to install your container on a Synology NAS (DS918+ with Intel CPU) within Docker application.

All seems good but volumes mounting, probably due to different user right between NAS directory and your container.
So while launching the container it stops with error since it cannot write to the associated volume.
"admin" user in Synology has uid=1024 and gid=100 while in your container "ignition" user has uid=999 and gid=999.
I tried to make \docker\ignition (linked to /var/lib/ignition) NAS folder accessible to "everyone" with whole rights but with no success.

![image](https://user-images.githubusercontent.com/51421790/58988652-69450380-87e2-11e9-9527-e0be631abe9a.png)

I have seen that other contaniers has proper environment variables (like PUID or PGID) to avoid this kind of problem.
Do you kindly have a solution for this issue?

Thanks in advance (for you wonderful job too!)

**Comment by thirdgen88** [comment]
I will take a look at what some other images have done on this.  I wanted to make sure that it wasn’t running as root, even in the container, but I agree, it would be helpful to be able to specify the UID/GID values.  Thanks for bringing it to my attention!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by morganzion** [comment]
See an example here: [https://gist.github.com/toniher/e465a45c4406d0e6c5123cf83403010b](url)

**Comment by proartsrl** [comment]
Dear Kevin, i really appreciate your job and i still have problems with UID and GID.

I need to change the UID and GID of "ignition" user in your contaiiner (999:999) to match the one in my Synology NAS (1024:100, that sadly i cannot change at all).
I tried hard (little experience...) to find a solution but no success at all.
I cannot change it from bash, useing "usermod", since "ignition" user is obviously used in ignition process.
So i am stuck and I'm kindly asking you if there is a way of doing this.

Thanks in advance

**Comment by thirdgen88** [comment]
@proartsrl I want you to be unstuck!  I was actually preparing the small adjustments to the base image hinted above earlier this week.  I will endeavor to commit those soon..  What I can do for you is push a custom image with your uid/gid settings to make it easy for you.  I will follow up soon.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thirdgen88** [comment]
@proartsrl, I have updated the image to fully support GID/UID specification on image build.  Unfortunately, this does require you to build the image from the repo here.  You can do so from the `8.0` folder with the command below (substitute the tag after `-t` to your liking):

    $ docker build --build-arg IGNITION_EDITION=full --build-arg IGNITION_DOWNLOAD_URL=https://files.inductiveautomation.com/release/ia/build8.0.6/20191112-1641/Ignition-linux-64-8.0.6.zip --build-arg IGNITION_DOWNLOAD_SHA256=7e69ea6f09a8bc0d67fd5fdd64102401115e3a0161f4258181285dfba8570c5d --build-arg IGNITION_UID=1024 --build-arg IGNITION_GID=100 -t kcollins/ignition:8.0.6-synology .

The command above can easily be constructed by looking at the `.travis.yml` file in the base of this repo.  That file is what is used by Travis CI to build and deploy my images to Docker Hub.  As a courtesy to get you going quickly, I've built an image (using the command above) and pushed to Docker Hub under the tag `kcollins/ignition:8.0.6-synology` with the specified UID/GID you mentioned in the issue.  You should be able to use that tag instead of `kcollins/ignition:8.0.6` when you create a container.

I'm going to close this issue, please open another one if you run into any other specific problems with the UID/GID functionality!  Thanks again for your patience!

**Comment by proartsrl** [comment]
You ARE amazing!!

Definitely tank you.


Marco Barbieri
engineer
Proart Srl

Via Paolucci de' Calboli 28
I-26100 CREMONA - ITALY
Phone:     +39-0372-32054
e-mail:     marco.barbieri@proartsrl.org

Think to the environment before printing this document

**** Riservatezza / Confidentiality ****
In ottemperanza al D.L. n. 196 del 30/6/2003 in materia di protezione dei
dati personali, le informazioni contenute in questo messaggio sono
strettamente riservate ed esclusivamente indirizzate al destinatario
indicato (oppure alla persona responsabile di rimetterlo al destinatario).
Vogliate tener presente che qualsiasi uso, riproduzione o divulgazione di
questo messaggio e vietato. Nel caso in cui aveste ricevuto questo
messaggio per errore, vogliate cortesemente avvertire il mittente e
distruggere il presente messaggio.

According to Italian law D.L. 196/2003 concerning privacy, if you are not
the addressee (or responsible for delivery of the message to such person)
you are hereby notified that any disclosure, reproduction, distribution or
other dissemination or use of this communication is strictly prohibited. If
you have received this message in error, please destroy it and notify us by
email


Il giorno mar 19 nov 2019 alle ore 03:46 Kevin Collins <
notifications@github.com> ha scritto:
