### ISSUE TITLE
Mysql 8 connector for Ignition 8.n

### ISSUE THREAD

**Issue by micahweber** [thirdgen88/ignition-docker#9]
The mysql connector is, by default, missing from the docker stack. It isn't a larte issue, but of you could include the .jar in the apin up, that would be fantastic.

**Comment by M0rfic** [comment]
@thirdgen88 Somewhat related, i'm using v8 images, and when upgrading to a new release i always have to re-upload the MYSql driver. Following your instructions when I migrated from 7 to 8 i have set up some additional modules i'm using, so they're just fine, but it keeps losing the driver. Have i missed something?

**Comment by thirdgen88** [comment]
I thought I had replied to this issue before, but perhaps I had just looked into it.  When you upload the MySQL driver through the gateway webpage, it gets placed in a separate place (`/var/lib/ignition/user-lib/jdbc`) that is outside of the `/var/lib/ignition/data` volume that we use for preserving gateway state.  The reason I have the module linkage working the way I do is that we want the base modules to be defined by the image (e.g. 8.0.5 or 8.0.6, etc) and the supplemental modules linked into place at runtime.

What I could do is add a similar feature for linking in custom JDBC drivers that would a) link the driver into place at `/var/lib/ignition/user-lib/jdbc` and b) adjust the record in the internal SQLite database table `JDBCDRIVERS` to specify the JAR file name.

I think this sounds like a good approach.  Let me know what you think.

**Comment by M0rfic** [comment]
Sounds good to me.

**Comment by M0rfic** [comment]
Hey mate,

First of all, a belated "happy new year"!
I almost missed your update as I did not get any notification about your commit. However it was the monthly docker "update version check time", so I randomly noted your docs update (speaking of which, there might be a typo in the beginning: "To automatically link and associated")

Just gave the new Ignition8 image a quick try using the MySql driver and it's working as expected, so thanks a bunch! I'll report back if I find anything funny, but so far so good.

Kind regards

**Comment by thirdgen88** [comment]
Closing this one out since I think the new JDBC integration is working well for folks.  Thanks @M0rfic and @micahweber
